import admin from "firebase-admin";

export const init = () => {
  const firestore = admin.firestore();
  const db = firestore.collection("randomQuestions");
  const counterDb = firestore.collection("counters");
  const batch = firestore.batch();
  const questions = [
    "Do you have a reoccurring dream?",
    "What's something that you think you may have been the only person in the world to ever do?",
    "Without saying the category, what are your top five?",
    "What's something that you find difficult, but you think in your mind it should be easy?",
    "Have you ever had a missed connection encounter?",
    "Do you think you were ever part of the popular crowd?",
    "How would a random stranger describe you? How accurate would that be?",
    "What would your dream day look like?",
    "What is something that someone does that will immediately turn you off?",
    "Do you consider yourself an introvert or an extrovert?",
    "What was the situation where you laughed the hardest you ever have?",
    "What's your opinion on social media?",
    "What is your opinion on tattoos?",
    "What's your current biggest worry?",
    "What is the messiest situation you've ever encountered?",
    "How well do you think you understand yourself?",
    "What is it that motivates yourself the most?",
    "Would you feel comfortable showing me the photos on your phone?",
    "What's the most uncomfortable situation you've ever found yourself in?",
    "What do you find you recently spend a lot of time wondering about?",
    "Do you have a bucket list?",
    "What is the best random act of kindness you've ever witnessed?",
    "What's something that you completely don't understand?",
    "What's your favorite thing to do when you're all alone?",
    "Who in your family can't you believe you're related to?",
    "How far back can you trace your family tree?",
    "What is your favorite spice?",
    "Do you have a favorite brand?",
    "What's some small thing you recently noticed?",
    "What song currently speaks to you the most?",
    "What line from a song has had the biggest impact on you?",
    "What do you like to do that's traditionally considered masculine?",
    "What assumption have you made that ended up being completely incorrect?",
    "On any given day, what do you think you spend the most time doing?",
    "What can you talk about for hours?",
    "What's something that you use regularly that you wish you didn't have to?",
    "If you had to ask yourself one question to get the most information out of you, what would that question be?",
    "What are some things don't you understand about the opposite sex?",
    "What's the story behind your favorite memento?",
    "Is there any place that you have no desire to visit? Why?",
    "What recent thing have you decided that you're completely over and done with?",
    "What memory have you been thinking about a lot lately?",
    "What is something that you like that your parents do?",
    "What is something immature you think your parents do?",
    "Do you have any unusual fears?",
    "What is your current favorite TV show? What was it 5 years ago?",
    "What is the last big argument you go into and who was it with?",
    "What argument did you have that looking back on was absolutely ridiculous?",
    "What question have people recently been constantly asking you?",
    "What is the most recent life lesson you've learned?",
    "What is socially acceptable today that you think won't be in 10 years?",
    "What piece of art has had a large impact on you?",
    "What book or movie character can you see in your own life?",
    "What are your favorite five words at the moment?",
    "Is there a part of your culture that you don't like?",
    "What's something that you know you should start, but haven't?",
    "What is the last encounter you had with a random stranger?",
    "What is something that has had a big impact on your that you observed from afar?",
    "What weird thing do you do when nobody else is around?",
    "Is there anything that most people find cute that creeps you out?",
    "How long does it take you to form an opinion about a person?",
    "Would the world be better or worse if superheroes existed?",
    "What's your plan for surviving a zombie invasion?",
    "What do you wish they would teach at school that they don't?",
    "If it was possible to transplant your brain to stay alive for another 100 years, would you?",
    "Have you ever had a terrible house guest? If so, what happened?",
    "Is time currently passing quickly or slowly for you?",
    "What is something you thought would be a great idea but was terrible when you actually did it?",
    "What animal do you think best reflects your personality?",
    "What is the most recent fact you learned that surprised you?",
    "What's your most recent passion?",
    "What was a past passion that you can't believe you were so passionate about?",
    "What's the most interesting conversation you eavesdropped on?",
    "What's the best comeback you've ever heard?",
    "Who is someone you recently thought about that you haven't seen or talked to in years?",
    "Who is someone you need to contact that you haven't?",
    "Is there anyone that you're wondering about and if they're okay?",
    "What are the top three characteristics you feel are important for a person?",
    "What is the most recent silly thing you did?",
    "What is something that will instantly annoy you?",
    "Does your family have any weird traditions?",
    "Do you have any apps on your phone that you've never used?",
    "What destination is at the top of your list to visit?",
    "What do you think people pretend to like when they really don't?",
    "Do you have any memories before the age of five?",
    "What do you remember most about your first crush?",
    "Have you ever done something embarrassing around a former crush?",
    "If you were to be famous for something, what would that be?",
    "Are you currently going through any type of phase?",
    "What doesn't exist, but should?",
    "Do you have a moment in your life you wish you could relive?",
    "In emergency situations, how do you react?",
    "What have you recently felt grateful for?",
    "Would you consider yourself decisive or indecisive?",
    "What are your top five snacks?",
    "If you had the choice to go back in time or into the future, which would you choose?",
    "What smell always brings back some type of memory?",
    "What's the best trick someone has ever played on you?",
    "Who was the last person you made happy and what did you do to do it?",
    "What's the most interesting thing you have in your pockets right now?",
    "Have you been given any good advice lately?",
    "What's the worst piece of advice you ever got from someone?",
    "What food do you have a love-hate relationship with?",
    "What foods did you used to like but don't anymore?",
    "What's something that you recently learned that everyone else already knew?",
    "Do you name inanimate objects?",
    "If you had to choose, would you rather be too hot or too cold?",
    "Are there any words that you simply can't stand?",
    "What uncommon thing would you encourage everyone to try once?",
    "What country sounds interesting but you know very little about it?",
    "How would you spend $1,000 to give the most happiness to the most number of people possible?",
    "What's the best compliment you ever received?",
    "Has someone ever done a random act of kindness to you?",
    "What is something you feel is unacceptable that is still being done today?",
    "What is the assumption that people make about you that's totally wrong?",
    "What is the last big goal you accomplished?",
    "What do you wish you had learned five years before you did?",
    "What song do you secretly sing in the shower?",
    "What's your favorite room in your house and why?",
    "What situation is sure to make you cry?",
    "If you had an extra hour a day that had to be allocated to one specific purpose, how would you use it?",
    "How well do you trust your gut feelings?",
    "Do you consider telling white lies to be okay?",
    "How much damage could your best friend do to you if you ever had a falling out?",
    "What's your go-to funny story now, but was horrendous at that moment?",
    'What does it mean to "live a good life" in your opinion?',
    "What is the most selfish thing you do that you're okay with?",
    "Of all the problems in the world, which one would you like to see solved first?",
    "What's the strangest situation you ever found yourself in?",
    "What is the strangest way you met one of your friends?",
    "Do you have a special project you're currently working on?",
    "How many chances do you give a person before you write them off?",
    "What recent experience made you feel old?",
    "What app or website completely changed your life?",
    "Is it better to read books in electronic form or actually hold the book?",
    "What's something interesting about you that few people know?",
    "Did you ever have a huge rival? Was the rivalry friendly or fierce?",
    "What's the best way you've found to calm yourself when you get stressed?",
    "What question do you have that nobody has been able to give you a good answer to?",
    "What was the unspoken scandal in your town when growing up?",
    "What activity do you do where your mind wanders in thoughts the most?",
    "What do you like best about yourself?",
    "What technology advance are you looking forward to in the future?",
    "What has been your biggest financial mistake?",
    "What is something that you absolutely will not put up with?",
    "What would someone who doesn't know you well be most surprised about?",
    "What is the funniest false thing you were able to convince others that's true?",
    "What is the oddest form of entertainment you enjoy?",
    "What is the next big purchase you're currently saving for?",
    "What recent situation was nearly a disaster, but you were able to prevent it?",
    "What were you most afraid of when you were younger? Do you still have that fear?",
    "What's most important to you about your school/work environment?",
    "What's the most difficult thing that you still do each day?",
    "Are you currently where you want to be in life?",
    "What little thing instantly tells you that a person is good?",
    "If there are 100 people, how many would be more patient than you?",
    "What is the next skill that you'd like to learn really well?",
    "What's something that really happened to you but nobody would believe unless they were there?",
    "What do you think is the most complex aspect about yourself?",
    "Is there a personality trait that you'd like to adopt from one of your friends?",
    "What is money to you?",
    "Can you describe your personal style?",
    "When you're by yourself, what do you usually think about?",
    "What do you love most about where you grew up?",
    "Do you have something special that picks you up when you feel down? What is it?",
    "If you had the opportunity to look through someone's email without them knowing, would you?",
    "What's an example of when you changed your mind?",
    "How would you describe your sense of humor? Can you give an example?",
    "What was a situation you thought would be terrible but you actually enjoyed it?",
    "Are you a planner or more of a go with whatever happens when it comes to travel?",
    "What would you be really good at if it wasn't for one thing?",
    "Why?",
    "Can you explain love?",
    "What does nobody want to talk about, but really should?",
    "If you had to pick a single word to describe this year so far, what would it be?",
    "What's stopping you?",
    "Who is the luckiest person you know?",
    "What was the last thing that truly disappointed you?",
    "What one thing would significantly make your life better?",
    "What's your biggest first world problem?",
    "What obscure interest do you have?",
    "If everyone here was a color, what color would each person be?",
    "If each person had a warning label, what would yours say?",
    "What do you consider the best decision you've made thus far in your life?",
    "What's the story behind your greatest treasure?",
    "If you could change the color of one thing, what would it be and why?",
    "What is your best shower thought?",
    "How do you best like your ice-cream?",
    "What was the last big mistake you made?",
    "What was a situation where you literally did a doubletake?",
    "Have you ever had to complain to management? Why?",
    "Have you ever seen a movie that you thought was better than the book?",
    "Where do you see yourself in 5 years?",
    "What is something that happened to you that you can't logically explain?",
    "What is the most unique cloud you've ever seen in the sky?",
    "Have you ever been at an event that you think will one day be in history books?",
    "Where's the next place you want to visit?",
    "If you could only ask one question to each person you meet, what would that question be?",
    "What topic can you bring up at a family gathering to instantly get everyone riled up?",
    "Have you ever had or witnessed a drop the mic moment?",
    "What thing from childhood do you still enjoy to this day?",
    "What are you currently doubting in your life?",
    "What is the quickest way for you to lose respect for someone?",
    "What's an interesting fact that you recently learned?",
    "What's the story behind why you replaced the last phone you had?",
    "What do you know how to do that's useless?",
    "Can you name 5 things you wouldn't do for a million dollars?",
    "Have you evet taken a long shot that worked out?",
    "What do you find is the most boring part of your life at the moment?",
    "What have you been thinking about lately that has kept you up at night?",
    "What was the last dream you can remember about?",
    "What's your favorite daily routine?",
    "What did you recently learn the hard way?",
    "Do you have a dream job in mind? What would it be?",
    "If you knew you could live forever, how would you spend your days differently?",
    "Where was your secret hiding place as a child?",
    "What is something you own that you have never used?",
    "What food have you never tried?",
    "What's the worst accident you ever had?",
    "Do you remember what the first school report you wrote was about?",
    "What is the most interesting class you've ever taken?",
    "What do you think is your most creative ability?",
    "If you had to name one thing that makes you stand out from others, what would that be?",
    "What's your story about breaking the law?",
    "What's your story about being under intense pressure and how did you handle it?",
    "What is the last thing that you totally overreacted to?",
    "What do you wish you had spent more time doing when you were younger?",
    "What thing have you been procrastinating about that you will begin doing today?",
    "What types of things do you doodle?",
    "How long did it take for you to come up with your current signature?",
    "What's your opinion on tipping?",
    "What's your knowing just enough to be dangerous story?",
    "What was your most recent experience of going down the rabbit hole?",
    "What's the one thing that you seem to constantly lose?",
    "What have you recently found to be ironic?",
    "What recent event have you seen that restored your faith in humankind?",
    "What do you find extremely difficult that most people find simple?",
    "When was the last memorable sunrise you witnessed?",
    "What is something that you would really like to try again?",
    "What do you see happening in your future?",
    "What was the last meltdown that you witnessed?",
    "What little thing do you do that you don't think many people notice?",
    "What do you try to do to make the world a little better?",
    "Who have you met only one time that left a huge impression on you?",
    "Do you have a nightmare travel story?",
    "What's the last thing you complained about?",
    "What's your close call story?",
    "Of all the things you've bought in your life, what has been the worst purchase?",
    "What's the most recent interesting conversation you had?",
    "What do you hope to be an expert about at some point in your life?",
    "What have you done that you didn't like, but would you be willing to give it another shot?",
    "How often do you find yourself daydreaming?",
    "What's something you find attractive that others may not?",
    "Do you people watch? If so, where do you like to do this most?",
    "What's your definition of success? Has it changed over time?",
    "What do you consider the most difficult food to eat?",
    "Do you, or did you in the past, have any strange habits?",
    "What do you wish you had more talent doing?",
    "What's the strangest thing you've ever found?",
    "What's the most amount of money you've ever found? What was the situation?",
    "What's something commonly do today that you think people will wonder why anyone would ever do that fifty years from now?",
    "Do you have any phobias?",
    "What's something others purchase that you simply can't understand why?",
    "What's the last thing that you gave up on? Are you happy or disappointed?",
    "Do you have any secret hobbies?",
    "What or who are you always willing to make time for?",
    "What's the story behind your last rant?",
    "What bad decision did you make that actually turned out to be a good decision?",
    "When you want to escape from everyone, where do you go?",
    "What about you do you seem to get the most comments about?",
    "How do you approach life?",
    "What old school skill set do you have?",
    "What's something that when you were learning it, you thought you'd never use it, but in reality, you ended up using it a lot?",
    "If someone were to sum you up with a phrase, what would that phrase be?",
    "What do you wish you understood better?",
    "How do you entertain yourself when you're bored?",
    "What have you recently realized you have been doing wrong?",
    "What's your opinion on naps?",
    "What's the next line to cross off your list?",
    "What's a food you vow never to eat?",
    "What's the biggest wager you've ever made?",
    'What\'s your "famous person" story?',
    "Have you ever been punished for something you didn't do?",
    "Have you ever let someone else get punished for something you did?",
    "What do you like to do that's considered touristy?",
    "What's simply too difficult?",
    "Why haven't you done it yet?",
    "What types of things do you procrastinate the most on?",
    "What's the most difficult choice you were asked to make?",
    "When are you most productive?",
    "What small stuff do you sweat even though you know you shouldn't?",
    "What's the story about the last time you cried?",
    "If you could change the length of each day to make it perfect for you, how many hours would it be?",
    "What's something uncomfortable but you feel everyone should experience at least once in their life?",
    "What have you found more helpful than you ever imagined it could be?",
    "Is there anything that makes you far angrier than it should?",
    'What was your last "ah-ha" moment?',
    "What food combination do you eat that makes others cringe?",
    "What do you know is bad for you but you continue to do it anyway?",
    "If you could have the attention of the world for one minute, what would you say?",
    "If you were required to have a job of some type but you didn't need the money from it to survive, what job would you choose?",
    "What's something in your fridge right now that should probably be thrown out?",
    "If it's raining outside, what activity do you most want to do?",
    "What is something that you don't mind waiting for?",
    "What is a restaurant you refuse to eat at and why?",
    "If you could remove something that exists in this world forever, what would it be?",
    "If you could have any person become a member of your family, who would you choose?",
    "What would be the best thing about losing your hearing?",
    "Would you prefer to leave where your hometown and never come back or stay in your hometown and never be able to leave?",
    "What is your opinion on social media?",
    "Do you have an app on your phone that you use even though you hate it?",
    "If you had to change the language you speak, which one would you choose?",
    "What do you consider to be the smartest thing you've ever done in your life so far?",
    "What is your biggest regret from the last month?",
    "If you could lock someone up and throw away the key, would you and if so, who would that be?",
    "What part of your body currently doesn't feel 100%?",
    "What part of the human face do you look at when you talk to someone?",
    "What is your current go-to song to dance to when nobody is around?",
    "What was the best thing you learned in the past year?",
    "If you could play a prank on any historical figure, who would you pick and what prank would you do?",
    "If you knew the winning lottery numbers, would you keep them to yourself or share with others?",
    "How would you describe someone who is wealthy?",
    "What would you do if you saw a giraffe on the side of the road?",
    "What is something that you find mildly annoying, but not annoying enough to do anything about?",
    "What's your favorite form of entertainment?",
    "What's something that you believe that most other people don't?",
    "If you were to work at a circus, what job would you choose?",
    "What's the most difficult thing about being you?",
    "What law have you broken the most in your life?",
    "Where is the strangest place you have fallen asleep?",
    "If you had to wear a hat for the next week, what type of hat would you choose?",
    "What would be the best and worst part of being a cat in your opinion?",
    "If you could choose the way you became a hero, what would the circumstances be?",
    "How do you make decisions?",
    "What's something that you believe you'll never be able to do well?",
    "What do you think would be the worst thing about being famous?",
    "What are the top three qualities you admire in others?",
    "Where is the last place you've been where you felt completely out of place?",
    "What are you currently juggling in your life?",
    "What holiday do you think more people should celebrate?",
    "What uncommon thing would you like to see become more common?",
    "What challenge would you like to see your best friend take on?",
    "If you could change one thing about your family, what would it be?",
    "What will be your go-to story when you're old?",
    "What's the last thing that you broke and how did it happen?",
    "What do you secretly hoard?",
    "What's one thing you think you should be doing more often?",
    "Do you enjoy people watching?",
    "What type of exercise do you like most?",
    "How do you usually react if you receive bad service?",
    "What's your opinion on cell phones?",
    "If you had to describe your current life as a movie, which movie would you choose?",
    "What's something that you never seem to get tired of doing?",
    "Which of your past teachers would you like to sit down with and talk to today?",
    "What do you find attractive that others might find unusual?",
    "What is your opinion on tattoos?",
    "What did you learn from the last book you read?",
    "What is the next thing you have on your to-buy list?",
    "How difficult is it for you to try new things?",
    "Where do you draw the line?",
    "If you were going to start your own business, what would it be?",
    "What is something you predict will exist in 10 years that doesn't today?",
    "What's something that you thought you'd have already done by now, but haven't?",
    "What's something that was completely out-of-character that you did?",
    "What's something that you would be willing to stay up all night to do?",
    "If you could only buy ten items at the grocery store to last the next week, what would you buy?",
    "What's the most spontaneous thing you've ever done?",
    "What's a situation when you look back you should have gone ahead and done it?",
    "If you could choose to be famous for something, what would it be?",
    "Do you believe there is only one other person in the world for you or many?",
    "If you had to walk away from one technology in your life, what would it be?",
    "If you were to devote your life to art, what type of art would that be?",
    "What is the easiest way to bring a smile to your face?",
    "What's the best part of rain?",
    "What's your current Golden Rule when it comes to living life?",
    "If you could assign one household chore to someone else, what would it be?",
    "What mode of transportation have you never tried?",
    "What sound will instantly melt your heart?",
    "What is something that you learned from simply watching a stranger?",
    "What was an experience you didn't think much about at the time, but it ultimately made you a stronger person?",
    "What's the embarrassing story that your parents used to tell others about you?",
    "At what age did you think you become an adult and when do you actually think you did?",
    "What the best thing that can happen in the first 5 minutes after waking up?",
    "What do you think is the most useful skill to know?",
    "Do you think you're more like your mom or your dad?",
    "How much money would you need in the bank to feel comfortable to retire today?",
    "What do you think is the most valuable resource?",
    "What's the last thing you did alone and you enjoyed?",
    "What do you believe is the biggest thing that's currently holding you back from success?",
    "What's the way you find yourself procrastinating most?",
    "What's something about you today that the old you would find surprising?",
    "How do you think your reality differs from others you know?",
    "What part of history do you find most interesting?",
    "What's something that is common today that humans will be embarrassed about doing in 50 years?",
    "What future year are you most looking forward to arriving?",
    "What is your current philosophy about money?",
    "What do you spend too much time doing?",
    "How many things you currently own do you think you could throw away and not notice a difference in your life?",
    "How long do you think you could survive on your own?",
    "What's something that you know that few other people know?",
    "Do you have a secret place?",
    "What do you do in secret that you're proud of?",
    "What's the last goal you set for yourself that you accomplished?",
    "If you were handed $500 at this moment, how would you spend it?",
    "Do you believe that money can make you happy?",
    "What's your favorite ritual?",
    "What photo have you recently seen that spoke to you?",
    "What has been your 15 minutes of fame up to this point?",
    "What's your good luck charm?",
  ];

  counterDb
    .doc("randomQuestions")
    .set({ count: admin.firestore.FieldValue.increment(questions.length) });
  questions.forEach((question, index) => {
    batch.set(db.doc(), { question, index });
  });
  batch.commit();
};

export const getRandom = async () => {
  const firestore = admin.firestore();
  const db = firestore.collection("randomQuestions");
  const counter = await firestore
    .collection("counters")
    .doc("randomQuestions")
    .get();
  const count = counter.data()?.count;
  const randomNumber = Math.floor(Math.random() * count + 1);
  const randomQuestion = await db
    .where("index", "==", randomNumber)
    .limit(1)
    .get();

  return randomQuestion.docs[0].data()?.question;
};
export const add = (question: string) => {};
